name: Monitoramento UHE Risoleta Neves

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Diagnóstico
        run: |
          pwd
          ls -la
          ls -la src

      - name: Testar Copernicus
        env:
          COPERNICUS_CLIENT_ID: ${{ secrets.COPERNICUS_CLIENT_ID }}
          COPERNICUS_CLIENT_SECRET: ${{ secrets.COPERNICUS_CLIENT_SECRET }}
        run: |
          python src/copernicus_api.py

      - name: Criar outputs
        run: mkdir -p outputs

      - name: Executar Pipeline
        env:
          COPERNICUS_CLIENT_ID: ${{ secrets.COPERNICUS_CLIENT_ID }}
          COPERNICUS_CLIENT_SECRET: ${{ secrets.COPERNICUS_CLIENT_SECRET }}
        run: |
          python main.py

      - name: Verificar Resultados
        run: |
          echo "Arquivos gerados:"
          find outputs -type f

      - name: Upload Artefatos
        uses: actions/upload-artifact@v4
        with:
          name: monitoramento-uhe
          path: outputs/
